export enum Errors {
    ERROR_CODE_UNDEFINED = 0,

    INVALID_ARGUMENT = 3,
    SIGNATURE_IS_INVALID = 301,

    NOT_FOUND = 5,
    CAULDRON_NOT_FOUND = 501,
    NFT_NOT_FOUND = 502,
    COLLATERAL_NOT_FOUND = 503,

    ALREADY_EXIST = 6,
    OFFER_EXIST = 601,

    PERMISSION_DENIED = 7,

    INTERNAL_ERROR = 13,

    UNAVAILABLE = 14,

    UNAUTHENTICATED = 16,
}
